# custom vars
TGT		:= yaddns
VERSION		:= 0.1
INFO		:= "\"http://gna.org/projects/yaddns\""

SERVICE		?= dyndns
LAYER		?= unix

EXTRA_LIBS	?= 
INC_DIRS	?= $(stagingdir)/include $(stagingdir)/usr/include
LIBS_DIRS	?= $(stagingdir)/lib $(stagingdir)/usr/lib

# global vars
CFLAGS		+= $(FPIC) -std=gnu99 -D_GNU_SOURCE \
		   -D__USER__="\"$(USER)\"" -D__HOST__="\"$(shell hostname)\"" \
		   -DNAME="\"$(TGT)\"" -DVERSION="\"$(VERSION)\"" \
                   -DINFO=$(INFO) \
		   -Wall -Wextra -O -Wwrite-strings -Wstrict-prototypes -Wuninitialized \
		   -Wunreachable-code \
		   -Wno-missing-braces  -Wno-missing-field-initializers \
		   -I./include \
		   $(foreach dir, $(INC_DIRS), -I$(dir))
LDFLAGS		+= -Wall $(foreach dir, $(LIBS_DIRS), -L$(dir))
LDLIBS		+= $(EXTRA_LIBS)

ifeq ($(MODE), debug)
MAKEFLAGS	+= 'DEBUG=y'
CFLAGS		+= -g -DDEBUG 
LDFLAGS		+= -Wall
endif

INSTALL		?= /usr/bin/install
ROOT		?= /usr/sbin

# files
core_sources	:= src/service.c src/layer.c $(wildcard src/*.c)
layer_source 	:= src/layers/$(LAYER).c
services_sources:= src/services/$(SERVICE).c
sources		:= $(core_sources) $(layer_source) $(services_sources)
objects		:= $(sources:.c=.o)

# rules
.PHONY: src/service.c src/layer.c

.PHONY: all
all: $(TGT)

$(TGT): $(objects)
	$(CC) $^ $(LDFLAGS) $(LDLIBS) -o $@

# Generate layer
src/layer.c:
	@echo > $@
	@echo '/* Autogenerated. Do NOT edit! */' >> $@
	@echo >> $@
	@echo >> $@
	@echo "#include \"defs.h\"" >> $@
	@echo >> $@
	@echo >> $@
	@echo "extern layer_t $(LAYER)_layer;" >> $@
	@echo >> $@
	@echo "layer_t *layer = &$(LAYER)_layer;" >> $@
	@echo >> $@

# Generate service
src/service.c:
	@echo > $@
	@echo '/* Autogenerated. Do NOT edit! */' >> $@
	@echo >> $@
	@echo >> $@
	@echo "#include \"defs.h\"" >> $@
	@echo >> $@
	@echo >> $@
	@echo "extern service_t $(SERVICE)_service;" >> $@
	@echo >> $@
	@echo "service_t *service = &$(SERVICE)_service;" >> $@
	@echo >> $@

.PHONY: install
install:
	$(INSTALL) -d $(ROOT)/
	$(INSTALL) -m 770 $(TGT) $(ROOT)/

.PHONY: clean
clean:
	find -name "*.o" -delete
	@rm -f $(TGT)

.PHONY: mrproper
mrproper: clean
